language: go

go:
  - master

install:
  - go get ./...
  - go get -u github.com/inconshreveable/mousetrap
  
script:
  - go build -o ./bin/flogowebhelper
  - GOOS=darwin go build -o ./bin/flogowebhelper-macos
  - GOOS=windows go build -o ./bin/flogowebhelper-win.exe

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  overwrite: true
  file:
    - "./bin/flogowebhelper"
    - "./bin/flogowebhelper-macos"
    - "./bin/flogowebhelper-win.exe"
  skip_cleanup: true
  on:
    tags: true
